cmake_minimum_required(VERSION 3.18)
file(READ "${SUITE}" content)
string(ASCII 30 RS)
get_filename_component(suite_name "${SUITE}" NAME_WE)
set(dir "${WORK}/semantic-${suite_name}")
file(MAKE_DIRECTORY "${dir}")
set(passed 0)
set(failed 0)
set(report "")
set(index 0)

string(APPEND content "${RS}")

while(TRUE)
    string(FIND "${content}" "${RS}" cut)
    if(cut EQUAL -1)
        break()
    endif()
    string(SUBSTRING "${content}" 0 ${cut} record)
    math(EXPR rest "${cut} + 1")
    string(SUBSTRING "${content}" ${rest} -1 content)
    string(STRIP "${record}" trimmed)
    if(trimmed STREQUAL "")
        continue()
    endif()
    math(EXPR index "${index} + 1")
    string(FIND "${trimmed}" "\n" nl)
    if(nl EQUAL -1)
        continue()
    endif()
    string(SUBSTRING "${trimmed}" 0 ${nl} expect)
    math(EXPR start "${nl} + 1")
    string(SUBSTRING "${trimmed}" ${start} -1 code)
    string(STRIP "${expect}" expect)
    file(WRITE "${dir}/case.wal" "${code}\n")
    execute_process(COMMAND "${WALNUT}" check "${dir}/case.wal"
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    set(ok FALSE)

    if(expect STREQUAL "OK")
        if(rc EQUAL 0)
            set(ok TRUE)
        endif()
    else()
        string(REGEX REPLACE "^ERR:" "" needle "${expect}")
        string(TOLOWER "${needle}" needle)
        string(TOLOWER "${out}${err}" hay)
        string(FIND "${hay}" "${needle}" pos)
        if(NOT pos EQUAL -1)
            set(ok TRUE)
        endif()
    endif()

    if(ok)
        math(EXPR passed "${passed} + 1")
    else()
        math(EXPR failed "${failed} + 1")
        string(APPEND report "case ${index} expected ${expect}\n${code}\n--- got (${rc}) ---\n${out}${err}\n\n")
    endif()
endwhile()

message(STATUS "${suite_name}: ${passed} passed, ${failed} failed")
if(failed GREATER 0)
    message(FATAL_ERROR "${report}")
endif()
